version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bitzomax_postgres
    environment:
      POSTGRES_DB: bitzomax
      POSTGRES_USER: bitzomax
      POSTGRES_PASSWORD: bitzomax_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    restart: always
    networks:
      - bitzomax-network

  backend:
    image: bitzomax-nl-backend
    container_name: bitzomax_backend
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bitzomax
      - SPRING_DATASOURCE_USERNAME=bitzomax
      - SPRING_DATASOURCE_PASSWORD=bitzomax_password
      - BITZOMAX_CORS_ALLOWED_ORIGINS=http://91.99.49.208:8000,http://bitzomax.nl,http://www.bitzomax.nl,https://bitzomax.nl,https://www.bitzomax.nl
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=500MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=500MB
    volumes:
      - uploads_data:/opt/bitzomax/uploads
    ports:
      - '8082:8082'
    restart: always
    networks:
      - bitzomax-network

  frontend:
    image: bitzomax-nl-frontend
    container_name: bitzomax_frontend
    ports:
      - '8000:80'
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
    networks:
      - bitzomax-network
networks:
  bitzomax-network:
    driver: bridge
volumes:
  postgres_data:
  uploads_data:
