-- Sample Video Data for BitZomax Platform
-- This script adds sample videos using existing uploaded files

-- Insert sample videos with existing file references
INSERT INTO videos (
    title, 
    description, 
    poem_text, 
    video_url, 
    cover_image_url, 
    hashtags, 
    content_type, 
    view_count, 
    like_count, 
    uploaded_by, 
    created_at, 
    updated_at,
    seo_title,
    seo_description,
    seo_keywords,
    spotify_link,
    amazon_link,
    apple_music_link,
    itunes_link,
    youtube_music_link,
    instagram_link
) VALUES 
(
    'Nederlandse Liedjes Mix', 
    'Een prachtige collectie van traditionele Nederlandse liedjes en moderne interpretaties. Perfect voor liefhebbers van Nederlandse muziek.', 
    'Zingende stemmen door de wind,
    Nederlandse woorden die ons vinden,
    In elke melodie, in elke toon,
    Klinkt ons verhaal, mooi en gewoon.',
    'videos/2650dc4f-22ee-427b-a695-511d13f797ac.mp4', 
    'covers/7c7c956f-1b20-40ec-bc87-d4747b330fd7.png', 
    'nederlandse liedjes, muziek, traditioneel, modern', 
    'FREE', 
    245, 
    12, 
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP,
    'Beste Nederlandse Liedjes - Traditioneel en Modern',
    'Ontdek de mooiste Nederlandse liedjes in deze unieke mix van traditionele en moderne muziek. Perfecte playlist voor Nederlandse muziekliefhebbers.',
    'nederlandse liedjes, nederlandse muziek, traditionele muziek, volksliederen',
    'https://open.spotify.com/playlist/example1',
    'https://amazon.com/music/example1',
    'https://music.apple.com/example1',
    'https://itunes.apple.com/example1',
    'https://music.youtube.com/example1',
    'https://instagram.com/bitzomax'
),
(
    'Moderne Poëzie & Muziek', 
    'Een experimentele combinatie van gesproken poëzie en moderne beats. Voor de liefhebbers van artistieke expressie.', 
    'Woorden dansen op de maat,
    Van moderne klanken, zo spontaan,
    Poëzie en muziek hand in hand,
    Samen vormen zij een nieuw verhaal.',
    'videos/5af9ab80-1a02-4614-bee4-6c9730578336.MOV', 
    'covers/84f48179-9487-49ba-a3e5-c934a87c70e0.png', 
    'poëzie, moderne muziek, experiment, kunst', 
    'PREMIUM', 
    89, 
    34, 
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP,
    'Moderne Poëzie meets Muziek - Artistieke Expressie',
    'Ervaar de kracht van gesproken woord gecombineerd met moderne muzikale composities. Een unieke artistieke ervaring.',
    'moderne poëzie, spoken word, experimentele muziek, kunst',
    'https://open.spotify.com/album/example2',
    'https://amazon.com/music/example2',
    'https://music.apple.com/example2',
    'https://itunes.apple.com/example2',
    'https://music.youtube.com/example2',
    'https://instagram.com/modernepoezienl'
),
(
    'Acoustic Sessions', 
    'Intieme akoestische uitvoeringen van bekende Nederlandse nummers. Puur en onvervalst.', 
    'Alleen de gitaar en stem,
    Zuiver en echt, zonder opsmuk,
    In deze stilte vinden we,
    De essentie van het lied.',
    'videos/62a8e8d9-53a3-497d-a3de-cf57e03cdf89.mp4', 
    'covers/c27f2415-db15-4ede-ab12-4a72b228aa26.png', 
    'akoestisch, intiem, gitaar, puur', 
    'FREE', 
    156, 
    28, 
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP,
    'Akoestische Nederlandse Muziek - Intieme Sessions',
    'Geniet van prachtige akoestische versies van bekende Nederlandse liedjes. Intiem, puur en onvervalst.',
    'akoestische muziek, gitaar, nederlandse covers, intieme muziek',
    'https://open.spotify.com/playlist/acoustic-nl',
    'https://amazon.com/music/acoustic',
    'https://music.apple.com/acoustic',
    'https://itunes.apple.com/acoustic',
    'https://music.youtube.com/acoustic',
    'https://instagram.com/acousticsessions'
),
(
    'Electronic Dutch Vibes', 
    'Een moderne twist op Nederlandse klassiekers met elektronische beats en synthesizers.', 
    'Digitale dromen in Nederlands geluid,
    Synthesizers die ons hart raken,
    Traditioneel ontmoet technologie,
    In een dans van bits en bytes.',
    'videos/75862ae2-564b-412b-89db-108d8abb4387.mp4', 
    'covers/d4a3122e-3c4a-4692-8a84-0bb9392c72b4.png', 
    'electronic, EDM, nederland, remix', 
    'PREMIUM', 
    198, 
    45, 
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP,
    'Electronic Dutch Music - Moderne Remixes',
    'Ervaar Nederlandse klassiekers in een nieuw jasje met elektronische beats en moderne productie.',
    'electronic music, dutch EDM, remixes, elektronische muziek',
    'https://open.spotify.com/playlist/electronic-dutch',
    'https://amazon.com/music/electronic',
    'https://music.apple.com/electronic',
    'https://itunes.apple.com/electronic',
    'https://music.youtube.com/electronic',
    'https://instagram.com/electronicdutch'
),
(
    'Folk Stories', 
    'Traditionele verhalen verteld door muziek en zang. Een reis door de Nederlandse folklore.', 
    'Oude verhalen in nieuwe klanken,
    Folklore die leeft en ademt,
    Generaties worden verbonden,
    Door melodieën uit vervlogen tijd.',
    'videos/87ca39c1-b864-437a-98de-9f688bec716a.MOV', 
    'covers/edf0ccb3-7526-4624-a82b-551c50e8243c.png', 
    'folk, verhalen, traditie, folklore', 
    'FREE', 
    134, 
    19, 
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP,
    'Nederlandse Folk Stories - Traditionele Verhalen in Muziek',
    'Ontdek de rijke Nederlandse folklore door prachtige muzikale verhalen die generaties verbinden.',
    'nederlandse folk, folklore, traditionele verhalen, volksverhalen',
    'https://open.spotify.com/playlist/folk-stories',
    'https://amazon.com/music/folk',
    'https://music.apple.com/folk',
    'https://itunes.apple.com/folk',
    'https://music.youtube.com/folk',
    'https://instagram.com/folkstories'
),
(
    'Contemporary Classics', 
    'Hedendaagse interpretaties van Nederlandse klassiekers door jonge talenten.', 
    'Nieuwe stemmen, oude liederen,
    Jeugd die tradities nieuw leven geeft,
    In elke noot klinkt respect,
    Voor wat was en wat komt.',
    'videos/aef18986-1470-42c5-9deb-e43c1b81b573.MOV', 
    'covers/fc805b62-aa3e-423b-941d-2b3a0d4b481f.JPG', 
    'contemporary, klassiek, jong talent, interpretatie', 
    'PREMIUM', 
    267, 
    52, 
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP,
    'Contemporary Nederlandse Klassiekers - Nieuwe Interpretaties',
    'Hoor hoe jonge talenten Nederlandse klassiekers een frisse, hedendaagse draai geven.',
    'contemporary music, nederlandse klassiekers, jong talent, nieuwe interpretaties',
    'https://open.spotify.com/playlist/contemporary',
    'https://amazon.com/music/contemporary',
    'https://music.apple.com/contemporary',
    'https://itunes.apple.com/contemporary',
    'https://music.youtube.com/contemporary',
    'https://instagram.com/contemporaryclassics'
),
(
    'Singer-Songwriter Sessions', 
    'Intieme optredens van Nederlandse singer-songwriters met persoonlijke verhalen.', 
    'Een gitaar, een stem, een verhaal,
    Persoonlijk en rauw,
    Elke singer-songwriter,
    Deelt een stukje ziel.',
    'videos/e7382e72-abab-4a1d-8b43-23a989a62385.MOV', 
    'covers/fe7fda94-1783-466e-81d9-3f8101c10a42.jpg', 
    'singer-songwriter, persoonlijk, verhalen, intiem', 
    'FREE', 
    178, 
    37, 
    1, 
    CURRENT_TIMESTAMP, 
    CURRENT_TIMESTAMP,
    'Nederlandse Singer-Songwriter Sessions - Persoonlijke Verhalen',
    'Intieme sessies met Nederlandse singer-songwriters die hun persoonlijke verhalen delen door muziek.',
    'singer-songwriter, nederlandse artiesten, persoonlijke verhalen, intieme muziek',
    'https://open.spotify.com/playlist/singer-songwriter',
    'https://amazon.com/music/singersongwriter',
    'https://music.apple.com/singersongwriter',
    'https://itunes.apple.com/singersongwriter',
    'https://music.youtube.com/singersongwriter',
    'https://instagram.com/singersongwriternl'
);

-- Update statistics for existing video (ID 3) if needed
UPDATE videos SET 
    view_count = 145,
    like_count = 23,
    seo_title = 'Bijzonder Nederlands Muziekmoment - BitZomax',
    seo_description = 'Ontdek deze bijzondere uitvoering van Nederlandse muziek op BitZomax.',
    seo_keywords = 'nederlandse muziek, bijzonder moment, muziekuitvoering'
WHERE id = 3;

-- Optional: Create some user interactions for the new videos (likes, views)
-- This would require knowing user IDs in the system

-- Show all videos after insertion
SELECT id, title, content_type, view_count, like_count, created_at FROM videos ORDER BY id;
